debug: false
server:
    port: 8000
spring:
    application:
        name: consumer-movie-ribbon-customizing-global

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
        enabled: true
    instance:
        prefer-ip-address: true
        appname: ${spring.application.name}
ribbon:
    eager-load:
        enabled: true
        clients: provider-user-ribbon-customizing-global
# 配置服务端可用信息
provider-user-ribbon-customizing-global:
    ribbon:
        listOfServers: localhost:8010,localhost:8020,
        ServerListRefreshInterval: 15000
