server:
    port: 8761
eureka:
    server:
        # 关闭自我保护
        enable-self-preservation: false
        # 清理服务器
        eviction-interval-timer-in-ms: 5000
    client:
        healthcheck:
            enabled: true
        service-url:
            defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:${server.port}/eureka/
        register-with-eureka: false
        fetch-registry: false
spring:
    security:
        user:
            name: admin
            password: 123456