server:
    port: 8800
spring:
    security:
        user:
            name: admin
            password: 123456
    application:
        name: sc-config-server
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/Wang-Jun-Chao/spring-all
                    searchPaths: '{application}'
eureka:
    client:
        service-url:
            defaultZone: http://admin:123456@localhost:8761/eureka/
    instance:
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
        appname: ${spring.application.name}